brew install bat
brew install fd
brew install ffmpeg
brew install figlet
brew install fish
brew install fx
brew install fzf
brew install git
brew install htop
brew install httpie
brew install httpstat
brew install jq
brew install lsd
brew install mise
brew install neofetch
brew install nmap
brew install pandoc
brew install ripgrep
brew install stow
brew install vim
brew install woff2
